[[footer]]
name = "About"
url = "about/"
weight = 2
[[footer]]
name = "PRODOTTI"
url = "project/"
weight = 3
[[footer]]
name = "Service"
url = "service/"
weight = 4
[[footer]]
name = "Pricing"
url = "pricing/"
weight = 5
[[footer]]
name = "FABBRICA"
url = "faq/"
weight = 6
[[footer]]
name = "CONTATTI"
url = "contact/"
weight = 7
[[main]]
name = "TELEFONO 1234 56789"
url = ""
weight = ""
[[main]]
name = "Home"
url = ""
weight = 1
[[main]]
name = "Project"
url = "project/"
weight = 3
[[main]]
name = "Blog"
url = "blog/"
weight = 4
[[main]]
hasChildren = true
name = "More"
weight = 5
[[main]]
name = "Service"
parent = "More"
url = "service/"
weight = 1
[[main]]
name = "Pricing"
parent = "More"
url = "pricing/"
weight = 2
[[main]]
name = "FAQ"
parent = "More"
url = "faq/"
weight = 3
[[main]]
name = "Contact"
url = "contact/"
weight = 6
