[[footer]]
name = "TELEFONO 0742 381401"
url = "contact/"
weight = "11"
[[footer]]
name = "DOWNLOAD"
url = "pricing/"
weight = "9"
[[footer]]
name = ""
url = "about/"
weight = 2
[[footer]]
name = "PRODOTTI"
url = "project/"
weight = 3
[[footer]]
name = "FABBRICA 4.0"
url = "faq/"
weight = 6
[[footer]]
name = "CONTATTI"
url = "contact/"
weight = 7
[[main]]
name = "DOWNLOAD"
url = "pricing/"
weight = "9"
[[main]]
name = "Home"
url = ""
weight = 1
[[main]]
name = "PRODOTTI"
url = "project/"
weight = "2"
[[main]]
name = "INFO"
parent = "More"
url = "service/"
weight = 1
[[main]]
name = "FABBRICA 4.0"
url = "faq/"
weight = 3
[[main]]
name = "CONTATTI"
url = "contact/"
weight = "4"
[[main]]
hasChildren = true
name = "More"
weight = "18"
